// Code generated by protoc-gen-go. DO NOT EDIT.
// source: meta.proto

package metapb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	commonpb "github.com/milvus-io/milvus-proto/go-api/commonpb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FieldIndexMeta struct {
	FieldID              int64                    `protobuf:"varint,1,opt,name=fieldID,proto3" json:"fieldID,omitempty"`
	CollectionID         int64                    `protobuf:"varint,2,opt,name=collectionID,proto3" json:"collectionID,omitempty"`
	IndexName            string                   `protobuf:"bytes,3,opt,name=index_name,json=indexName,proto3" json:"index_name,omitempty"`
	TypeParams           []*commonpb.KeyValuePair `protobuf:"bytes,4,rep,name=type_params,json=typeParams,proto3" json:"type_params,omitempty"`
	IndexParams          []*commonpb.KeyValuePair `protobuf:"bytes,5,rep,name=index_params,json=indexParams,proto3" json:"index_params,omitempty"`
	IsAutoIndex          bool                     `protobuf:"varint,6,opt,name=is_auto_index,json=isAutoIndex,proto3" json:"is_auto_index,omitempty"`
	UserIndexParams      []*commonpb.KeyValuePair `protobuf:"bytes,7,rep,name=user_index_params,json=userIndexParams,proto3" json:"user_index_params,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *FieldIndexMeta) Reset()         { *m = FieldIndexMeta{} }
func (m *FieldIndexMeta) String() string { return proto.CompactTextString(m) }
func (*FieldIndexMeta) ProtoMessage()    {}
func (*FieldIndexMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{0}
}

func (m *FieldIndexMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldIndexMeta.Unmarshal(m, b)
}
func (m *FieldIndexMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldIndexMeta.Marshal(b, m, deterministic)
}
func (m *FieldIndexMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldIndexMeta.Merge(m, src)
}
func (m *FieldIndexMeta) XXX_Size() int {
	return xxx_messageInfo_FieldIndexMeta.Size(m)
}
func (m *FieldIndexMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldIndexMeta.DiscardUnknown(m)
}

var xxx_messageInfo_FieldIndexMeta proto.InternalMessageInfo

func (m *FieldIndexMeta) GetFieldID() int64 {
	if m != nil {
		return m.FieldID
	}
	return 0
}

func (m *FieldIndexMeta) GetCollectionID() int64 {
	if m != nil {
		return m.CollectionID
	}
	return 0
}

func (m *FieldIndexMeta) GetIndexName() string {
	if m != nil {
		return m.IndexName
	}
	return ""
}

func (m *FieldIndexMeta) GetTypeParams() []*commonpb.KeyValuePair {
	if m != nil {
		return m.TypeParams
	}
	return nil
}

func (m *FieldIndexMeta) GetIndexParams() []*commonpb.KeyValuePair {
	if m != nil {
		return m.IndexParams
	}
	return nil
}

func (m *FieldIndexMeta) GetIsAutoIndex() bool {
	if m != nil {
		return m.IsAutoIndex
	}
	return false
}

func (m *FieldIndexMeta) GetUserIndexParams() []*commonpb.KeyValuePair {
	if m != nil {
		return m.UserIndexParams
	}
	return nil
}

type CollectionIndexMeta struct {
	MaxIndexRowCount     int64             `protobuf:"varint,1,opt,name=maxIndexRowCount,proto3" json:"maxIndexRowCount,omitempty"`
	IndexMetas           []*FieldIndexMeta `protobuf:"bytes,2,rep,name=index_metas,json=indexMetas,proto3" json:"index_metas,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CollectionIndexMeta) Reset()         { *m = CollectionIndexMeta{} }
func (m *CollectionIndexMeta) String() string { return proto.CompactTextString(m) }
func (*CollectionIndexMeta) ProtoMessage()    {}
func (*CollectionIndexMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{1}
}

func (m *CollectionIndexMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectionIndexMeta.Unmarshal(m, b)
}
func (m *CollectionIndexMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectionIndexMeta.Marshal(b, m, deterministic)
}
func (m *CollectionIndexMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectionIndexMeta.Merge(m, src)
}
func (m *CollectionIndexMeta) XXX_Size() int {
	return xxx_messageInfo_CollectionIndexMeta.Size(m)
}
func (m *CollectionIndexMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectionIndexMeta.DiscardUnknown(m)
}

var xxx_messageInfo_CollectionIndexMeta proto.InternalMessageInfo

func (m *CollectionIndexMeta) GetMaxIndexRowCount() int64 {
	if m != nil {
		return m.MaxIndexRowCount
	}
	return 0
}

func (m *CollectionIndexMeta) GetIndexMetas() []*FieldIndexMeta {
	if m != nil {
		return m.IndexMetas
	}
	return nil
}

func init() {
	proto.RegisterType((*FieldIndexMeta)(nil), "milvus.proto.meta.FieldIndexMeta")
	proto.RegisterType((*CollectionIndexMeta)(nil), "milvus.proto.meta.CollectionIndexMeta")
}

func init() { proto.RegisterFile("meta.proto", fileDescriptor_3b5ea8fe65782bcc) }

var fileDescriptor_3b5ea8fe65782bcc = []byte{
	// 356 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xc1, 0x4a, 0xeb, 0x40,
	0x14, 0x65, 0xda, 0xf7, 0x5a, 0x7b, 0x53, 0xab, 0x8d, 0x9b, 0x41, 0x10, 0x62, 0x56, 0x41, 0x68,
	0x03, 0xfa, 0x05, 0xb6, 0x45, 0x28, 0x52, 0x89, 0x59, 0xb8, 0x70, 0x13, 0xa6, 0xe9, 0x58, 0x07,
	0x32, 0x99, 0x90, 0x99, 0xd1, 0xf6, 0x03, 0xfc, 0x0f, 0xbf, 0xcf, 0xaf, 0x90, 0x99, 0xa4, 0x96,
	0xa0, 0x8b, 0xee, 0xee, 0x3d, 0x37, 0xe7, 0x9e, 0x93, 0x73, 0x07, 0x80, 0x53, 0x45, 0xc6, 0x45,
	0x29, 0x94, 0x70, 0x87, 0x9c, 0x65, 0x6f, 0x5a, 0x56, 0xdd, 0xd8, 0x0c, 0xce, 0xfb, 0xa9, 0xe0,
	0x5c, 0xe4, 0x15, 0xe4, 0x7f, 0xb5, 0x60, 0x70, 0xc7, 0x68, 0xb6, 0x9a, 0xe7, 0x2b, 0xba, 0x59,
	0x50, 0x45, 0x5c, 0x0c, 0xdd, 0x17, 0x8b, 0xcc, 0x30, 0xf2, 0x50, 0xd0, 0x8e, 0x77, 0xad, 0xeb,
	0x43, 0x3f, 0x15, 0x59, 0x46, 0x53, 0xc5, 0x44, 0x3e, 0x9f, 0xe1, 0x96, 0x1d, 0x37, 0x30, 0xf7,
	0x02, 0x80, 0x99, 0x55, 0x49, 0x4e, 0x38, 0xc5, 0x6d, 0x0f, 0x05, 0xbd, 0xb8, 0x67, 0x91, 0x07,
	0xc2, 0xa9, 0x3b, 0x01, 0x47, 0x6d, 0x0b, 0x9a, 0x14, 0xa4, 0x24, 0x5c, 0xe2, 0x7f, 0x5e, 0x3b,
	0x70, 0xae, 0x2f, 0xc7, 0x0d, 0x9b, 0xb5, 0xc1, 0x7b, 0xba, 0x7d, 0x22, 0x99, 0xa6, 0x11, 0x61,
	0x65, 0x0c, 0x86, 0x15, 0x59, 0x92, 0x3b, 0x83, 0x7e, 0x25, 0x51, 0x2f, 0xf9, 0x7f, 0xe8, 0x12,
	0xc7, 0xd2, 0xea, 0x2d, 0x3e, 0x1c, 0x33, 0x99, 0x10, 0xad, 0x44, 0x62, 0x61, 0xdc, 0xf1, 0x50,
	0x70, 0x14, 0x3b, 0x4c, 0xde, 0x6a, 0x25, 0x6c, 0x1c, 0xee, 0x02, 0x86, 0x5a, 0xd2, 0x32, 0x69,
	0xc8, 0x75, 0x0f, 0x95, 0x3b, 0x31, 0xdc, 0xf9, 0x5e, 0xd2, 0xff, 0x40, 0x70, 0x36, 0xdd, 0x87,
	0xf5, 0x93, 0xf8, 0x15, 0x9c, 0x72, 0xb2, 0xb1, 0x7d, 0x2c, 0xde, 0xa7, 0x42, 0xe7, 0xaa, 0x8e,
	0xfe, 0x17, 0x6e, 0x02, 0xac, 0xdc, 0x98, 0x63, 0x4a, 0xdc, 0xfa, 0xcb, 0x8c, 0x7d, 0x00, 0xcd,
	0xab, 0xc6, 0xd5, 0x55, 0x4c, 0x29, 0x27, 0x8f, 0x30, 0x60, 0x62, 0x47, 0x59, 0x97, 0x45, 0x3a,
	0xe9, 0x99, 0x41, 0x64, 0xc8, 0x11, 0x7a, 0x0e, 0xd7, 0x4c, 0xbd, 0xea, 0xa5, 0xf9, 0xa7, 0xb0,
	0xfa, 0x68, 0xc4, 0xc4, 0xae, 0xb2, 0x0a, 0xe1, 0x5a, 0x8c, 0x48, 0xc1, 0x42, 0x23, 0x54, 0x2c,
	0x3f, 0x11, 0x5a, 0x76, 0x2c, 0x7e, 0xf3, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x23, 0xbc, 0x8e, 0x72,
	0x7d, 0x02, 0x00, 0x00,
}
